### ISSUE TITLE
Open link in new tab

### ISSUE THREAD

**Issue by webflo** [Chi-teck/environment-switcher#1]
Can we add a option to open the environment link in a new tab? A global option to change the behaviour is probably enough.

**Comment by Chi-teck** [comment]
I would rather add support for middle button. Right now to open environment in a new tab you can use  CTRL + click.

**Comment by webflo** [comment]
`CTRL + click` does not work on OS X. Because CMD (window.event.metaKey) is the modifier key on OS X.

**Comment by Chi-teck** [comment]
Middle button click was added in 1.4.0.

**Comment by webflo** [comment]
Cool Thanks, i try it later todax
